name: Build resource_observer test image and run tests on it
run-name: Build resource_observer test image and run tests on it - started by ${{ github.actor }}
on:
  pull_request:
    types: [opened, synchronize]
    paths:
    - 'docker_images/resource_observer/**'
  workflow_dispatch:


jobs:
  build_image:
    runs-on: self-hosted
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Build image
        run: bash -x build.sh resource_observer build
      - name: Build test image and run tests
        run: bash -x docker_images/run_test.sh resource_observer
